name: 'Oryx Demo Action'
description: 'Build and deploy an Azure WebApp'
branding:
  icon: cloud
  color: white
inputs:
  sourceDirectory:
    description: 'The source directory of the repository.'
    required: false
  language:
    description: 'The platform language of the web app.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}